jobs:
  determinator:
    outputs:
      default_branch: ${{ steps.determinate.outputs.default_branch }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      id: determinate
      run: "DEFAULT_BRANCH=$(gh api \\\n  -H \"Accept: application/vnd.github+json\"\
        \ \\\n  -H \"X-GitHub-Api-Version: 2022-11-28\" \\\n  /repos/VazkiiMods/Botania\
        \ | jq -r .default_branch)\n# Add refs/heads/ for easier comparison with github.ref\
        \ below\necho \"default_branch=refs/heads/$DEFAULT_BRANCH\" >> \"$GITHUB_OUTPUT\"\
        \n"
  main:
    needs: determinator
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ hashFiles('web/Gemfile.lock') }}
        path: 'web/vendor

          '
    - continue-on-error: true
      name: Install deps
      run: 'sudo apt-get install bundler

        bundle install --deployment

        '
      working-directory: web
    - continue-on-error: true
      name: Build website
      run: bundle exec jekyll build
      working-directory: web
    - continue-on-error: true
      name: Print branch names for debugging
      run: 'echo ''Current branch: ${{ github.ref }}''

        echo ''Default branch: ${{ needs.determinator.outputs.default_branch }}''

        '
    - continue-on-error: true
      if: ${{ github.ref == needs.determinator.outputs.default_branch }}
      name: Import ssh keys
      run: 'umask go=

        mkdir -p ~/.ssh

        echo ''${{ secrets.VIOLET_MOON_WEBSERVER_SSH_KEY }}'' > ~/.ssh/id_ed25519

        echo ''${{ vars.BOTANIAWEB_KNOWN_HOST }}'' >> ~/.ssh/known_hosts

        '
    - continue-on-error: true
      if: ${{ github.ref == needs.determinator.outputs.default_branch }}
      name: Push
      run: rsync -rl web/_site/ customer@botaniaweb.playat.ch:/var/www/botaniamod_net
name: Build and Push website
on:
  repository_dispatch:
    types: trigger-ga___pushweb.yml
